allow user specified cuda streams for concurrent transfer/execution
flatironinstitute/finufft pull request #330
Opened 2023-08-02 19:48 UTC by blackwer

This PR adds an option to the cufinufft_opts struct to specify the cuda stream, specified
as a void*, which can be trivially cast from cudaStream_t. Default behavior should be the NULL
stream, which is the default cuda 'legacy' stream. Therefore the end user won't have to change
anything to retain the default behavior, but can implement concurrency where desired more easily.

This functionality is exposed through the python API as well by specifying the keyword argument
'gpu_stream=cupy.cuda.Stream().ptr' (or other relevant stream pointer) to the plan constructor.

Limited tests on 3d type-2 transforms show that a simple front/back buffer swap approach can
achieve a 1.25x boost over best-effort synchronous execution (pinned memory, re-used buffers,
etc), and ~3x speedup over the naive implementation (no pinning, alloc and return).

This commit builds on #326 

see: python/cufinufft/examples/example3d2many_async.py

2023-08-06 05:34 UTC, chaithyagr commented
Great to get this up working !
However i was wondering if this api where a plan and a particular nufft runs on a given stream is a good idea. 
I would rather prefer to have a plan and then run execute on any stream defined on it's call. What do you think

2023-08-06 11:45 UTC, blackwer commented
> I would rather prefer to have a plan and then run execute on any stream defined on it's call. What do you think

I considered this but went with this scheme for a number of reasons, the main points here

1. simplicity: the public API signatures remain the same. One of our goals is to make the `cufinufft` API the same as the `finufft` API. Eventually we'd like to merge things so that there is no `cufinufft` as a separate entity. 
2. consistency: by setting the stream on the plan object, there is no concern about swapping streams on an active plan mid-execution. one plan should not run two streams simultaneously, since there is internal state that is input dependent in some cases. A new setpts would break EVERYTHING, for example. I think the spreader also modifies internal buffers, but I'm not 100% sure off the top of my head. Regardless, even if there isn't, this would limit the implementation in the future, and is just another thing to worry about internally and more difficult to test for issues.

2023-08-06 12:13 UTC, paquiteau commented
Hi, 
I am not against making cufinufft and finufft closer, but from my point of view, having a clear separation of finufft and cufinufft is great. I can easily install one or the other depending on the hardware I have access to. Anyway It's not our codebase so do whatever is best in your interest. 

Regarding the streams and plans, I see two cases from our usage in mri-nufft:
- Run `n_trans` transforms truly in parallel, using streams. But from what I understood of the above, that is not possible. 
- switch the plan's stream between two transform call. This would be close to what @chaithyagr has done for gpuNUFFT[^1]. This at least would allow for concurrent copy and execution (which would be ideal for multi-coil MRI)
  - If this is not possible, having multiples plans with shared memory (e.g. for the NUpts locations and others parameters) could be an alternative ? 
 
Also I am fine with the stream setup being only accessible via the guru interface, if that make things easier, IMO concurrency is already some advance feature and the (expert) end-user would probably use the guru interface anyway. 

Keep up the great work, we are following it with great interest, and will be happy to test it in real conditions when its ready, the speedup are very encouraging for doing so in the near future !


[^1]: See notably the profiling timeline in this issue: https://github.com/flatironinstitute/cufinufft/issues/126

2023-08-06 13:24 UTC, blackwer commented
> Run `n_trans` transforms truly in parallel, using streams. But from what I understood of the above, that is not possible.

Yes. the cards are saturated at your problem sizes at least. Attempts at increasing kernel execution loads has ended up a net negative in every configuration I played with. A very clear net negative. The memory bandwidth is capped out for a single transform (spreading is hard), so there's not much more to be gained without improving the spreading algorithms, which is on the agenda.

> This at least would allow for concurrent copy and execution (which would be ideal for multi-coil MRI) 

The current scheme in this PR allows for that. Am I misunderstanding something? I know it takes two plans, but... I actually got best performance with `n_trans = 1` in my buffer swapping example. So having multiple plans like this uses considerably much less GPU memory than the large `n_trans` method. It adds to a bit more code complexity on the user end, but this could be encapsulated in a wrapper class pretty easily I think.

2023-09-08 17:36 UTC, blackwer commented
@janden I had to bump the `jenkins` build to `cuda-11.2` to support `cudaMallocAsync`. This could be engineered around, but I'm ~100% sure it's not worth it but wanted to check. Thoughts?

2023-09-16 21:35 UTC, janden commented
> @janden I had to bump the `jenkins` build to `cuda-11.2` to support `cudaMallocAsync`. This could be engineered around, but I'm ~100% sure it's not worth it but wanted to check. Thoughts?

Fine with me. As far as I can tell, CUDA 11.0 is June 2020 while CUDA 11.2 is December 2020, so shouldn't be restricting users too much here.

2023-12-11 14:01 UTC, janden requested changes
This looks great! Some questions. Likely exposing my ignorance of CUDA than anything else, but hoping you can enlighten me a bit here.

2023-12-11 14:21 UTC, blackwer commented on src/cuda/3d/interp3d_wrapper.cu
> +    const char *tpbstr = getenv("CUFINUFFT_INTERP3D_TPB");
I'd like to be able to set it, but I think it should just be placed in a feature request for now. The TPB parameters can sometimes make a very big performance impact, and autocalculating them has been lackluster in my attempts so far.

2023-12-11 14:36 UTC, blackwer commented on src/cuda/3d/spread3d_wrapper.cu
> +    cudaStreamSynchronize(stream);
The `cudaMemcpyAsync` just above is copying the integer `totalNUpts` from device to host. We then immediately need the *value* of that integer on the host here, which means that the memcpy kernel needs to have actually executed. 

The solution to this is much more complicated. To avoid these `device -> host` transfers you need to just dynamically allocate the arrays in GPU device code, rather than host code. Arrays allocated in this way are completely opaque to the host. You can't allocate/deallocate them or do anything to them from the host side. This is a bit of pain to bookkeep, unfortunately, though I have started working on a clean way to wrap all this code up in a proof-of-concept.

I'd rather take the code as it is now, and just say it's `async[ish]`, though we should discuss.

2023-12-11 15:28 UTC, blackwer commented on include/cufinufft/impl.h
> +    cudaStreamSynchronize(stream);
Addressed in [eddf0c9](https://github.com/flatironinstitute/finufft/pull/330/commits/eddf0c9abc2646c1aa55b145c7868edeb96ab9b5)

2023-12-11 15:28 UTC, blackwer commented on src/cuda/3d/interp3d_wrapper.cu
> +    const char *tpbstr = getenv("CUFINUFFT_INTERP3D_TPB");
Addressed in [d44ca74](https://github.com/flatironinstitute/finufft/pull/330/commits/d44ca749fd9fc12f39dd8d0565e0c0119ace5be1)

2023-12-11 15:29 UTC, blackwer commented on test/cuda/fseries_kernel_test.cu
> +                                         opts.nspread, NULL);
Addressed in 115f0d0

2023-12-11 16:55 UTC, janden commented on include/cufinufft/impl.h
> +    cudaStreamSynchronize(stream);
Got it. Thanks!

2023-12-11 17:00 UTC, janden commented on src/cuda/3d/spread3d_wrapper.cu
> +    cudaStreamSynchronize(stream);
Ok makes sense. I guess the big question is how much of a speed-up can we expect from removing these device syncs? Is it worth it?

2023-12-11 17:04 UTC, blackwer commented on src/cuda/3d/spread3d_wrapper.cu
> +    cudaStreamSynchronize(stream);
No real performance benefit. Just that we will block on the host side, holding up the user's code if they want proper async.

2023-12-11 17:29 UTC, merged