Update `setup.py` for cufinufft
flatironinstitute/finufft pull request #393
Opened 2023-12-12 11:51 UTC by janden

Some smaller stuff like error messages and URLs but also fixing install bug under Rocky 8 and Ubuntu 20.04 (was already fixed for finufft). Finally, moves the `cufinufftc` C extension into the `cufinufft` package instead of leaving it in the site-packages root.

2023-12-12 15:03 UTC, blackwer requested changes
This looks mostly good. It needs the fix you made with `<stdint.h>` that's been merged in on my setup.

The extra compile step actually created a new issue for me though. 
If you're using a different `gcc` via a `PATH` environment variable than the one used to compile `python`, this breaks because it can't find the standard library headers. This is _very_ common in HPC environments. I had to supply `CC=gcc pip install blahblah` to get it to work. 

I think we should seriously consider scrapping this whole `ext_modules` business and just copy the shared library directly into the install path. See my thoughts and frustrations at https://github.com/flatironinstitute/finufft/issues/389#issuecomment-1850926589

Edit: I'm drafting a PR that removes `ext_modules` requirements.

2023-12-12 17:03 UTC, ahbarnett commented
I also have similar problems with master's local py build now.
If I build lib by CMake then
```
pip3 install -e python/finufft
python3 python/finufft/test/run_accuracy_tests.py
```
gives errors due to
```
    self._handle = _dlopen(self._name, mode)
OSError: /home/alex/miniconda3/envs/py310/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/alex/numerics/finufft/lib/libfinufft.so)
```
If I move the libs into lib/ and lib-static/ no different.
Also `CC=gcc pip3 ...` did not fix it.
If I build by classic makefile it works fine (my make.inc has nothing in it).
Very confusing...

2023-12-12 21:05 UTC, blackwer commented
> Also `CC=gcc pip3 ...` did not fix it.

I suppose cmake is finding a different compiler than `make` is using. Annoying. Can you try #394 for me?

2023-12-12 21:16 UTC, janden commented
> If you're using a different `gcc` via a `PATH` environment variable than the one used to compile `python`, this breaks because it can't find the standard library headers.

Ok, that's obnoxious. Weird that this works with cufinufft then since it's the same type of thing.

> Edit: I'm drafting a PR that removes `ext_modules` requirements.

Ok I'm going to scale down this PR to avoid touching the `ext_modules` stuff.

2023-12-12 22:36 UTC, janden commented
Closing since #394 subsumes this.

2023-12-18 15:07 UTC, janden commented
Reopening since we probably want to merge this before the release.

2023-12-18 22:20 UTC, janden commented
@ahbarnett @blackwer Removed the new compilation step so hopefully this works better now. Let me know if you have any problems. The only substantive change here is the change in library search path which should avoid the need for specifying `LD_LIBRARY_PATH` when installing the package.

2023-12-19 15:03 UTC, blackwer commented
This looks good to me. @WardBrian pointed out that this method doesn't actually place requirements on the python ABI version, since we don't actually use any of the python API in our C code. Similar to my PR on this, we can override the platform tags to build one shared object for all python distributions. It's a few line fix (you basically just inherit from bdist_wheel and override some methods). I think we should just go ahead and do it here.

https://github.com/joerick/python-ctypes-package-sample/blob/main/setup.py

2023-12-19 21:20 UTC, janden commented
> @WardBrian pointed out that this method doesn't actually place requirements on the python ABI version, since we don't actually use any of the python API in our C code.

Makes sense.

> Similar to my PR on this, we can override the platform tags to build one shared object for all python distributions. It's a few line fix (you basically just inherit from bdist_wheel and override some methods). I think we should just go ahead and do it here.

Ok. I'm going to merge this and open another PR to experiment a bit with this.

2023-12-19 21:20 UTC, merged